[package]
name = "belvedere-applet"
description = "Belvedere panel applet for COSMIC"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
belvedere-core.workspace = true
chrono = "0.4.45"
libcosmic = { git = "https://github.com/pop-os/libcosmic.git", version = "1.0.0", features = ["applet", "tokio", "wgpu"] }
tokio = { version = "1.53.2", features = ["rt-multi-thread", "macros", "time"] }
zbus = { version = "5.19.0", default-features = false, features = ["tokio"] }
